version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/definitions.json:/opt/definitions.json:ro
      - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=access
      - MINIO_SECRET_KEY=secret123
    volumes:
      - ./minio/config.json:/config.json:ro
      - ${DATA_DIR}:/data
    user: ${CURRENT_UID}
    command: minio --config-dir / server /data
    depends_on:
      - rabbitmq
  flask:
    build: flask
    ports:
      - "5000:5000"
  # notifications:
  #   build: notifications
